### ISSUE TITLE
Passing arguments for I18n routes seems not working

### ISSUE THREAD

**Issue by aristipp** [ADmad/cakephp-i18n#27]
Maybe i'am doing something totally wrong, but for now i do not see whats wrong with this code.

**Works**
http://foo.bar/en/main

**Works** if i omit `['routeClass' => 'ADmad/I18n.I18nRoute']`
http://foo.bar/main
http://foo.bar/main/sub/123456

The parameter becomes '123456'

**Works not**
http://foo.bar/en/main/sub/123456

The parameter stays null.

```
public function test($id = null) {}

Router::scope('/main', function ($routes) {
        $routes->connect(
            '/',
            [
                'controller'    => 'Pages',
                'action'        => 'index',
            ]
            ,[ 'routeClass' => 'ADmad/I18n.I18nRoute']
        );
        $routes->connect(
            '/sub/:id',
            [
                'controller'    => 'Pages',
                'action'        => 'test',
            ],
            ['routeClass' => 'ADmad/I18n.I18nRoute'],
            [
                'pass'  => [
                    'id',
                ],
                'id' => '[0-9]+'
            ]
        );
    });
```

**Comment by ADmad** [comment]
Your second `$routes->connect()` statement is incorrect. The `pass` and `id'` key should be in same array as `routeClass`. `RouteBuilder::connect()` has only 3 arguments not 4.

**Comment by aristipp** [comment]
Thanks alot!
