### ISSUE TITLE
Switch language

### ISSUE THREAD

**Issue by frankbrise** [ADmad/cakephp-i18n#28]
Hi,

How can I switch between two language and keep the same controller/action with the Url helper or Html helper with your plugin?

Thank you.

**Comment by ADmad** [comment]
This plugin just provides routing, link generation is up to you.

**Comment by frankbrise** [comment]
I know, but why this line doen't work with the plugin?

`<?= $this->Html->link(__('English'), ['lang' => 'en']);?>`

**Comment by daerentis** [comment]
Right, this Plugin isn't meant to build Urls.
You could append the `setPersist()` Function to your Route:

```
  $routes->connect(
    '/destinations/:slug/:id',
    ['controller' => 'Destinations', 'action' => 'view'],
    ['routeClass' => 'ADmad/I18n.I18nRoute']
  )->setPersist(['slug', 'id']);
```
