### ISSUE TITLE
command 'i18n' in plugin 'ADmad/I18n' was not aliased, conflicts with another shell

### ISSUE THREAD

**Issue by be-mohand** [ADmad/cakephp-i18n#30]
Hi,

Thank you for your great work with the I18n plugin.

Everything works great but I have a notice in my logs. 

I don't have much details except {"scope":["shell-dispatcher"]}.

Don't hesitate to tell me how I can help ^^

**Comment by ADmad** [comment]
Exactly what command did you run?

**Comment by be-mohand** [comment]
The debug appears in my log everytime I exec bin/cake migrations migrate (it appears twice) or bin/cake orm_cache clear (it appears only once).

**Comment by ADmad** [comment]
Okay, [this](https://github.com/cakephp/cakephp/blob/master/src/Console/ShellDispatcher.php#L269) is what generates that log entry. The shell dispatcher warns of potential naming conflict but there's no real error. One can use `bin/cake i18n` to access the core `I18nShell` and `bin/cake ADmad/I18n.i18n` to access the I18n shell provided my plugin.

You can open an issue on cakephp core repo if you want.

**Comment by be-mohand** [comment]
I am ok with this behavior. Maybe there is a good reason for this log, even if there's no real error with your plugin. So I won't open an issue on cakephp core repo.

Thanks a lot for your investigation.
