### ISSUE TITLE
Handling multi-domain application localization

### ISSUE THREAD

**Issue by smarek** [ADmad/cakephp-i18n#37]
Hi, is it possible with current state of plugin to have different language route for different domain?

ie. myapp.cz -> lang=cs_CZ, myapp.eu -> lang=en_US

Currently the language is persisted in URL (either as query param or route element), but would be cool, if instead of `myapp.cz/cs_CZ/:controller/:action` one could omit the `cs_CZ/` part and have the language set by current domain of request

**Comment by ADmad** [comment]
If you want to set language based on domain then you don't need the `I18nRoute` class. Just set routes normally and set locale using I18n::setLocale() based on domain name.
