### ISSUE TITLE
Custom Redirects 

### ISSUE THREAD

**Issue by bergwerkweb** [ADmad/cakephp-i18n#38]
Hey there,

after activating this plugin i seem to have trouble connecting custom routes - specifically a route not following the /:controller/:action convention.

for example i use:
$routes->connect('/mycompany', ['controller' => 'Companies',"action"=>"view"],['routeClass' => 'ADmad/I18n.I18nRoute']);

CakePHP then generates the currect URL:
$this->Url->build(["controller"=>"companies","action"=>"view"]) results in https://myserver.com/en/mycompany
However, when visiting the link, an error occurs:
Error: MycompanyController could not be found.

Do I have to pass a special parameter anywhere?

thanks in advance!

**Comment by ADmad** [comment]
Using I18nRoute with custom routes works just fine. Please use on of CakePHP's help forum for support.
