### ISSUE TITLE
Routing prefix

### ISSUE THREAD

**Issue by smarek** [ADmad/cakephp-i18n#39]
Related to #34, i'm having '/' scope with only custom defined routes (no dashed/inflected/... routes), that works well with the plugin

However I also have '/admin' scope that has DashedRoute as default, because admin controllers are allowed to be dynamic.

Is it possible to have one prefix/scope handled by i18n middleware, and other not?

**Comment by ADmad** [comment]
I really understand your problem. `I18nMiddleware` only does redirection if URL is `/`, not for any other URL.

**Comment by smarek** [comment]
Not sure if you reply to correct ticket? This issue is tackling that there is no documentation on how to use your plugin along with prefixes (recommended way of administrative interfaces by cakephp-docs) and/or combining it with other router classes (dashed/inflected/...)

Maybe you have some app that is code-public and uses your plugin, so we can take more inspiration from?

**Comment by smarek** [comment]
Also, related issue, accessing not-defined-route in default scope, will show routes that are available, such as 'Users:login'
![2019-09-19-145622_1295x72_scrot](https://user-images.githubusercontent.com/384824/65245897-c17fe700-daed-11e9-8076-251860d1f53b.png)

However accessing defined-route in scope that is not routed by I18nRoute, will show this trace, about AuthComponent->_isLoginAction not resolving the 'Users:login' route, and it shows with controller name lowercase below the stacktrace
![2019-09-19-145647_567x911_scrot](https://user-images.githubusercontent.com/384824/65245959-e2483c80-daed-11e9-943d-d2691884b0ca.png)
![2019-09-19-145700_1304x77_scrot](https://user-images.githubusercontent.com/384824/65246019-0015a180-daee-11e9-8a8a-afdbda90e339.png)

Is it possible, that this kind of issue is caused by this plugin, or should i go upstream to cakephp/cakephp and report it?

**Comment by ADmad** [comment]
The readme already states 
`Note: I18nRoute extends core's DashedRoute so the URL fragments will be inflected accordingly.`

So if you want to use `InflectedRoute` go look elsewhere :)

**Comment by ADmad** [comment]
> Maybe you have some app that is code-public and uses your plugin, so we can take more inspiration from?

Sorry that's not something I am interested in doing. This is something I built for myself and shared it as I thought other's might find it useful. So whoever can figured out how to use it is welcome and for those who can't all I can say is sorry.

**Comment by ADmad** [comment]
The missing route error you have shown isn't directly related to the plugin. It depends on what routes you have or haven't setup.

**Comment by smarek** [comment]
> So if you want to use `InflectedRoute` go look elsewhere :)
I don't want to, that was just an example

>This is something I built for myself and shared it as I thought other's might find it useful. So whoever can figured out how to use it is welcome and for those who can't all I can say is sorry.
Well that is something worth stating on top of readme, that you provide no support, and maybe close the issues here and link only to cakephp support platforms (slack/discourse/...)

>The missing route error you have shown isn't directly related to the plugin. It depends on what routes you have or haven't setup.
I was not presenting missing route, but the strange thing that when the route goes missing, it is listed with controller name lowercase in the trace, however i'm going to put it as upstream issue

Thank you anyway for your comments
