### ISSUE TITLE
Default route missing

### ISSUE THREAD

**Issue by smarek** [ADmad/cakephp-i18n#40]
Currently with this peace of code

```php
Router::defaultRouteClass(I18nRoute::class);

$routerCallbacks = function (RouteBuilder $routes) {
    $routes->setRouteClass(I18nRoute::class);

    $routes->connect('/', ['controller' => 'Public', 'action' => 'home'], ['routeClass' => DashedRoute::class]);
    $routes->connect('/', ['controller' => 'Public', 'action' => 'home']);
};

Router::scope('/', $routerCallbacks);
```

Routing the default slash route works, without the first route with explicit different routeClass, '/' route always throws NotFoundException (Error: A route matching "/" could not be found.)

Is documentation lacking, or should I18nMiddleware create default route to redirect to correct/default language, and it's not happening with me?

**Comment by ADmad** [comment]
The `I18nRoute` only sets route with lang prefix. It doesn't set any route for `/` so the error you get is expected.

What I do personally is set an additional route for `/` with core `Route` class. Then the `I18nMiddleware` intercepts requests to `/` and redirects to a lang prefixed URL as per it's config.

**Comment by smarek** [comment]
So basically something similar to what I did? Would be great if you could put a example-code up in the docs / readme.md

**Comment by ADmad** [comment]
Yeah similar to what you did. No one has asked this question before so I presume everyone understand what was required :)

**Comment by smarek** [comment]
:) thank you for explanation, but please put it in the docs, the usage of the plugin is not really obvious
