### ISSUE TITLE
Redirect to default language

### ISSUE THREAD

**Issue by smarek** [ADmad/cakephp-i18n#41]
I've done this quite ugly solution, to tackle RouteMissingException on URLs that did not contain correct language

```php
// src/Middleware/LanguageRedirectMiddleware.php
<?php

namespace App\Middleware;

use Cake\Core\Configure;
use Cake\Core\InstanceConfigTrait;
use Cake\Http\ServerRequest;
use Psr\Http\Message\ResponseInterface;
use Zend\Diactoros\Response\RedirectResponse;

class LanguageRedirectMiddleware
{
    use InstanceConfigTrait;

    public function __construct($config = [])
    {
    }

    public function __invoke(ServerRequest $request, ResponseInterface $response, $next)
    {
        $langs = Configure::read('I18n.languages');
        $segments = explode('/', $request->getRequestTarget());
        $segment = $segments[1];
        if (!in_array($segment, $langs)) {
            $response = new RedirectResponse(
                '/' . $langs[0] . $request->getRequestTarget(),
                302
            );
            return $response;
        }
        return $next($request, $response);
    }
}
```
And registering the middleware before routing middleware and error handler
```php
// src/Application.php
    public function middleware($middlewareQueue)
    {
        $middlewareQueue
            ->add(new AssetMiddleware())
            ->add(LanguageRedirectMiddleware::class)
            ->add(ErrorHandlerMiddleware::class)
            ->add(new RoutingMiddleware($this, '_cake_routes_'));
    }
```

I'd expect cakephp-i18n to redirect to default language route, if the lang param is not present, and i did not find any nicer solution. So just sharing fyi and maybe for inspiration for others.

Also currently it does not redirect to default language, but the first language in I18n.languages configure key

**Comment by ADmad** [comment]
> I'd expect cakephp-i18n to redirect to default language route, if the lang param is not present...

That's your choice, but I don't do that. For e.g if my site serves only `en` and `fr` languages and some one accesses URL `/de/foo` then I want them to a 404 error page in production (the missing route error is only in debug mode). I see it as a non existent URL like any other and don't see any need to treat it differently.

Redirecting for non existent languages is probably bad for SEO too, but I am no experts on SEO.
