### ISSUE TITLE
Configuration for DbMessagesLoader 

### ISSUE THREAD

**Issue by ninbarbu** [ADmad/cakephp-i18n#43]
Hi,

I'm using cake 3.8.4 and I try to cofigure DbMessagesLoader.
I only have a single MVC to try it.
I did the Installation/Usage/DbMessagesLoader part of the documentation (including table creation).

I changed a line in the example :
`I18n::setConfig('default', function ($domain, $locale) {`
with 
`I18n::config('default', function ($domain, $locale) {`
because `I18n::setConfig` doesn't exist in 3.8.4

The bootstrap section looks like this :

```
Cache::setConfig(Configure::consume('Cache'));
ConnectionManager::setConfig(Configure::consume('Datasources'));
TransportFactory::setConfig(Configure::consume('EmailTransport'));
Email::setConfig(Configure::consume('Email'));
Log::setConfig(Configure::consume('Log'));
Security::setSalt(Configure::consume('Security.salt'));

// Configure I18n to use DbMessagesLoader for default domain. You need to do
// this for each domain separately.
I18n::config('default', function ($domain, $locale) {
    return new \ADmad\I18n\I18n\DbMessagesLoader(
        $domain,
        $locale
    );
});
```

When I run the script `bin/cake ADmad/I18n.i18n extract`, the CLI seems right, but the table "i18n_messages" is not populated.

What did I miss ? Does it still work with cake 3.8.x ?

**Comment by ninbarbu** [comment]
Yes, I baked the views with CLI and every echo has `__()`
Here is the result of the keythe CLI
```
$ bin/cake ADmad/I18n.i18n extract
Current paths: None
What is the path you would like to extract?
[Q]uit [D]one
[C:\wamp64\www\paiement\src\] > C:\wamp64\www\paiement\src\

Current paths: C:\wamp64\www\paiement\src\
What is the path you would like to extract?
[Q]uit [D]one
[D] >

Would you like to extract the messages from the CakePHP core? (y/n)
[n] >

Would you like to merge all domain strings into the default domain? (y/n)
[n] >


Extracting...
---------------------------------------------------------------
Paths:
   C:\wamp64\www\paiement\src\
---------------------------------------------------------------
==========================================================================> 100%
Done.
```

When I simply extract the `__()` with `bin/cake i18n extract`, the src/Locale/default.pot is correctly generated.
But I just realized that the basic traslation with the .po files in src/Locale/en_US, src/Locale/fr_FR does not work either.
I don't think there's a link but ..., never know ...

**Comment by ADmad** [comment]
Hope you were able to figure out the problem. Closing as the issue has gone stable and there have been no other reports of similar problem.
