### ISSUE TITLE
View routes get their ID dropped

### ISSUE THREAD

**Issue by ntoka** [ADmad/cakephp-i18n#44]
Hi, we can't get the plugin configured to preserve view action IDs when switching language. Our route connect looks like this:
`$routes->connect('/news/view/*', ['controller' => 'News', 'action' => 'view', 'plugin' => 'Blog'], ['routeClass' => 'ADmad/I18n.I18nRoute']);`

when we're in a uri /fr/news/view/1 - switching language to english gives us a uri /en/news/view/

The switcher in template looks like this:

`<?= $this->Html->link(__('EN'), ['lang' => 'en'], ['class' => $ref_lang == 'en' ? 'lang-btn active' : 'lang-btn']);?>`

Any ideas why this can be caused?

**Comment by ADmad** [comment]
No route values get automatically preserved/persisted unless you use use `persist` option. That's how routing works in general, it not specific to the I18nRouter. Also for having a route value persisted you need to use a route element like `/news/view/:id` in your case and then persist `id`, using `*` won't work for persisting.

P.S. This is a bug tracker not a help form. Please use one of CakePHP's help forums in future.
