### ISSUE TITLE
sell command(s) isn't compatible with cakephp 4

### ISSUE THREAD

**Issue by Islam-Baraka** [ADmad/cakephp-i18n#47]
i get an errors on extracting command with the plugin name 
my environment  is :
windows 10 
php 7.2
cakephp 4.0.4
steps to create the error is try to execute the command 
cake ADmad/I18n.i18n extract
bin/cake ADmad/I18n.i18n extract
i'm getting the following error 

`C:\Users\ElSngab\Desktop\cakeapp\base\bin>cake admad/i18n.i18n extract
Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Warning Error: preg_match(): Unknown modifier '1'
In [C:\Users\ElSngab\Desktop\cakeapp\base\vendor\cakephp\cakephp\src\Console\Exception\MissingOptionException.php, line 97]

Unknown command `cake admad/i18n.i18n`. Run `cake --help` to get the list of commands.
`

and when i change the DS to \ i get none existing command 

Unknown command `cake admad\i18n.i18n`. Run `cake --help` to get the list of commands.

and when i run cake --help i dont get the command in the list also i can find the commands from other plugin  such as BootstrapUI 

please note that i had a successfully implement this plugin on older version of cake 3 and the project was going fine but when i did this new project on cake 4 i get this errors 

many thanks in advance for your time and effort

**Comment by ADmad** [comment]
Update to `2.0.0-beta2` release and running `bin/cake` will show you the commands provided by the plugin.
