### ISSUE TITLE
Remove :lang in default language URLs

### ISSUE THREAD

**Issue by Erwane** [ADmad/cakephp-i18n#48]
Hi,
Do you think it's relevant to remove lang part in default language ?

`/` -> home in english (instead of `/en`)
`/fr` -> home in french

**Comment by ADmad** [comment]
If up to you what URL scheme you want to use for you all. If you don't want lang prefix for default language then don't set routes for it using the `I18nRoute` class.

**Comment by Erwane** [comment]
closed so fast ...
I really want `lang` but only when not in default language. And of course it is not cool to write urls twice, for default lang and for others (with nearly same url).
What's the problem with that ?

**Comment by ADmad** [comment]
> And of course it is not cool to write urls twice, for default lang and for others (with nearly same url).

The router doesn't support optional route params, so setting route 2 twice is the only option. What you want might be achievable using a single route if/when https://github.com/cakephp/cakephp/pull/14643 is merged. You can open a pull request in future and I will reconsider.
