### ISSUE TITLE
Extract task warns about Invalid marker content

### ISSUE THREAD

**Issue by smarek** [ADmad/cakephp-i18n#50]
Having gettext handle DB provided content, extract shell task newly warns about **Invalid marker content**, either silently or with `--marker-error` verbosely, something that in 3.x was not warned about, is it possible to suppress the 'errors' completely or do I have to live with the notice **marker error(s) detected. => Use the --marker-error option to display errors.** from now on?
Thank you 

```
# ./bin/cake admad/i18n extract --paths 'src/' --exclude 'src/Controller/Admin/' --exclude 'templates/Admin/' --extract-core no --merge no --languages en_US,fr_FR -v --marker-error
Processing /var/www/app.domain.com/src/Controller/Component/AppComponent.php...                                                                                                     
Invalid marker content in /var/www/app.domain.com/src/Controller/Component/AppComponent.php:257                                                                                     
* __(                                                                                                                                                                                          
$entity->label)
```

**Comment by ADmad** [comment]
Not sure I understand the problem. Your issue is regarding Cake 3.x compatible version or Cake 4? 
Displaying errors for invalid markers is disabled by default https://github.com/ADmad/cakephp-i18n/blob/master/src/Command/I18nExtractCommand.php#L332.

**Comment by smarek** [comment]
Using Cake 4, Issue is the 'invalid marker' indication, that did not exist in Cake 3 version, and i'm not sure how to get rid of it (ie. suppress the indication at all or resolve the invalid markers by changing code)

**Comment by ADmad** [comment]
As I pointed out display of errors for invalid markers is disabled by default, so I still don't understand what you are trying to get rid of.

**Comment by smarek** [comment]
The warnings, how can i fix the code so it is not warned about

**Comment by ADmad** [comment]
This is an issue tracker not a help forum. The I18n function calls like `__()` generating invalid marker warnings has nothing to do with this plugin's code.
