### ISSUE TITLE
Compatibility with cakedc/i18n

### ISSUE THREAD

**Issue by impronta48** [ADmad/cakephp-i18n#61]
Hi,
I've got a mixed environment where I share a table between two projects.

Project A is based on cake 2.x (and cakedc/i18n)
Project B is based on cake 4.x (and cakephp-i18n)

The two projects share table Routes.
My problem is that in 2.x the i18n table stores in field __Model__ the plural: **Routes**
while in 4.x cakephp-i18n, stores the singular **Route**

Is there a way to override this behaviour? And store the plural in this plugin? Any idea how I could mantain compatibility?

Thanks
Massimo

**Comment by ADmad** [comment]
This plugin doesn't use any i18n table with `Model` field.
